//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NdefLibrary.Ndef {
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NdefExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NdefExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NdefLibrary.Ndef.NdefExceptionMessages", typeof(NdefExceptionMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to instantiate new record from incompatible record..
        /// </summary>
        internal static string ExInvalidCopy {
            get {
                return ResourceManager.GetString("ExInvalidCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments for LaunchApp must not be empty..
        /// </summary>
        internal static string ExLaunchAppArgumentsEmpty {
            get {
                return ResourceManager.GetString("ExLaunchAppArgumentsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to assemble LaunchApp payload: length of platform / AppID tuple more than 255 characters..
        /// </summary>
        internal static string ExLaunchAppPlatformLength {
            get {
                return ResourceManager.GetString("ExLaunchAppPlatformLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to assemble LaunchApp payload: at least one platform / AppID tuple is required..
        /// </summary>
        internal static string ExLaunchAppPlatformMissing {
            get {
                return ResourceManager.GetString("ExLaunchAppPlatformMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one platform / app ID tuple needs to be defined..
        /// </summary>
        internal static string ExLaunchAppPlatformsEmpty {
            get {
                return ResourceManager.GetString("ExLaunchAppPlatformsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a Windows Phone platform ID, please supply the 36 character product ID containing only hexadecimal characters and &apos;-&apos;..
        /// </summary>
        internal static string ExLaunchAppWpId {
            get {
                return ResourceManager.GetString("ExLaunchAppWpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient address must not be empty..
        /// </summary>
        internal static string ExMailtoAddressEmpty {
            get {
                return ResourceManager.GetString("ExMailtoAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient address does not appear to be valid..
        /// </summary>
        internal static string ExMailtoAddressNotValid {
            get {
                return ResourceManager.GetString("ExMailtoAddressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndef parse error: Message Begin flag present after first record..
        /// </summary>
        internal static string ExMessageBeginLate {
            get {
                return ResourceManager.GetString("ExMessageBeginLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndef parse error: Expected Message Begin missing in first record..
        /// </summary>
        internal static string ExMessageBeginMissing {
            get {
                return ResourceManager.GetString("ExMessageBeginMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndef parse error: Message End flag present after last record..
        /// </summary>
        internal static string ExMessageEndLate {
            get {
                return ResourceManager.GetString("ExMessageEndLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndef parse error: Invalid chunked data, Id Length != 0..
        /// </summary>
        internal static string ExMessageInvalidChunkedId {
            get {
                return ResourceManager.GetString("ExMessageInvalidChunkedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndef parse error: Invalid chunked data, Type Length != 0..
        /// </summary>
        internal static string ExMessageInvalidChunkedType {
            get {
                return ResourceManager.GetString("ExMessageInvalidChunkedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndef parse error: Malformed NDEF Message, missing begin or end..
        /// </summary>
        internal static string ExMessageNoBeginOrEnd {
            get {
                return ResourceManager.GetString("ExMessageNoBeginOrEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndef parse error: Partial chunk not empty or typeNameFormat not 0x06 as expected..
        /// </summary>
        internal static string ExMessagePartialChunk {
            get {
                return ResourceManager.GetString("ExMessagePartialChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndef parse error: Unexpected end of message..
        /// </summary>
        internal static string ExMessageUnexpectedEnd {
            get {
                return ResourceManager.GetString("ExMessageUnexpectedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code must be 5 characters..
        /// </summary>
        internal static string ExNearSpeakLanguageWrongLength {
            get {
                return ResourceManager.GetString("ExNearSpeakLanguageWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online ID must be set..
        /// </summary>
        internal static string ExNearSpeakNoCloudId {
            get {
                return ResourceManager.GetString("ExNearSpeakNoCloudId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code must be defined..
        /// </summary>
        internal static string ExNearSpeakNoLanguage {
            get {
                return ResourceManager.GetString("ExNearSpeakNoLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to speak must not be empty..
        /// </summary>
        internal static string ExNearSpeakNoText {
            get {
                return ResourceManager.GetString("ExNearSpeakNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductName for Nokia Accessories record must not be empty..
        /// </summary>
        internal static string ExNokiaAccessoriesProductEmpty {
            get {
                return ResourceManager.GetString("ExNokiaAccessoriesProductEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number for Nokia Accessories must not be empty..
        /// </summary>
        internal static string ExNokiaAccessoriesSerialEmpty {
            get {
                return ResourceManager.GetString("ExNokiaAccessoriesSerialEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number must be 19 chars, decimal numbers only..
        /// </summary>
        internal static string ExNokiaAccessoriesSerialFormat {
            get {
                return ResourceManager.GetString("ExNokiaAccessoriesSerialFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The raw URI can only be retrieved if the URI is not abbreviated by the record..
        /// </summary>
        internal static string ExRawUriNoAbbreviation {
            get {
                return ResourceManager.GetString("ExRawUriNoAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Type set for record..
        /// </summary>
        internal static string ExRecordNoType {
            get {
                return ResourceManager.GetString("ExRecordNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id must not be set for middle or terminating record (TNF = Unchanged)..
        /// </summary>
        internal static string ExRecordUnchangedId {
            get {
                return ResourceManager.GetString("ExRecordUnchangedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record with TNF Unchanged must have an empty type name..
        /// </summary>
        internal static string ExRecordUnchangedTypeName {
            get {
                return ResourceManager.GetString("ExRecordUnchangedTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body text for SMS record must not be empty..
        /// </summary>
        internal static string ExSmsBodyEmpty {
            get {
                return ResourceManager.GetString("ExSmsBodyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number for SMS record must not be empty..
        /// </summary>
        internal static string ExSmsNumberEmpty {
            get {
                return ResourceManager.GetString("ExSmsNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social user name must not be empty..
        /// </summary>
        internal static string ExSocialNoUser {
            get {
                return ResourceManager.GetString("ExSocialNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri of Smart Poster ust not be empty..
        /// </summary>
        internal static string ExSpUriEmpty {
            get {
                return ResourceManager.GetString("ExSpUriEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number for telephone record must not be empty..
        /// </summary>
        internal static string ExTelNumberEmpty {
            get {
                return ResourceManager.GetString("ExTelNumberEmpty", resourceCulture);
            }
        }
    }
}
